## 基本設定
api:
  dashboard: true
  insecure: false

# Dockerプロバイダーの設定
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: "/etc/traefik"

# エントリーポイント設定
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

# Let's Encrypt設定
certificatesResolvers:
  letsencrypt:
    acme:
      email: "${ACME_EMAIL}"
      storage: "/etc/traefik/acme/acme.json"
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: web

# アクセスログとエラーログ
log:
  level: "DEBUG"

# Prometheusメトリクス
metrics:
  prometheus: {} 