## 基本設定
api:
  dashboard: true

# Dockerプロバイダーの設定
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic_conf.yml

# エントリーポイント設定
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

# Let's Encrypt設定
certificatesResolvers:
  letsencrypt:
    acme:
      email: "${ACME_EMAIL}"  # 環境変数から取得
      storage: /etc/traefik/acme/acme.json
      httpChallenge:
        entryPoint: web

# アクセスログとエラーログ
log:
  level: INFO

# Prometheusメトリクス
metrics:
  prometheus: {} 